# Generated by Django 2.2 on 2020-08-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('F', 'is forming'), ('S', 'sent for processing'), ('P', 'paid'), ('O', 'is proceeding'), ('R', 'ready'), ('C', 'cancel')], default='F', max_length=1, verbose_name='status'),
        ),
    ]
