# Generated by Django 2.2 on 2020-06-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200621_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_prod',
            field=models.CharField(blank=True, max_length=50, verbose_name='type of product'),
        ),
    ]
