# Generated by Django 2.2 on 2020-06-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_type_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_prod',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type of product'),
        ),
    ]
